vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end

vim.o.background = "light"
vim.g.colors_name = "xcode-pastel"

local colors = {
	bg = "#ffffff",
	fg = "#656f81",
	ui_fg = "#434343",
	line_numbers = "#d4d4d4",
	line_numbers_act = "#818c96",
	line_hl = "#eeeeee",
	selection = "#b5d5ff",
	comment = "#89c0b4",
	preprocessor = "#ef8776",
	string = "#ee81b0",
	number = "#8adcfb",
	keyword = "#ee81b0",
	storage = "#ee81b0",
	builtin_const = "#ee81b0",
	class = "#89c0b4",
	tag = "#aa83e4",
	library_func = "#aa83e4",
	library_class = "#aa83e4",
	sidebar_bg = "#f8f8f7",
	sidebar_border = "#e5e5e5",
	status_bg = "#f6f6f5",
	status_fg = "#666666",
	tab_active_bg = "#f7f7f6",
	tab_inactive_bg = "#e9e9e8",
	search_match = "#a8ac94",
}

local highlights = {
	Normal = { fg = colors.fg, bg = colors.bg },
	NormalNC = { fg = colors.fg, bg = colors.bg },
	Cursor = { fg = colors.bg, bg = "#000000" },
	CursorLine = { bg = colors.line_hl },
	CursorColumn = { bg = colors.line_hl },
	ColorColumn = { bg = colors.line_hl },
	LineNr = { fg = colors.line_numbers, bg = colors.bg },
	CursorLineNr = { fg = colors.line_numbers_act, bg = colors.line_hl, bold = true },
	Visual = { bg = colors.selection },
	Search = { bg = "#fae49e", fg = "#434343" },
	IncSearch = { bg = "#f7be7e", fg = "#000000", bold = true },
	SignColumn = { bg = colors.bg },
	FoldColumn = { fg = colors.line_numbers, bg = colors.bg },
	Folded = { fg = colors.status_fg, bg = colors.sidebar_bg },
	VertSplit = { fg = colors.sidebar_border, bg = colors.bg },
	WinSeparator = { fg = colors.bg, bg = colors.bg },
	StatusLine = { fg = colors.status_fg, bg = colors.status_bg },
	StatusLineNC = { fg = colors.line_numbers, bg = colors.status_bg },
	TabLine = { fg = colors.status_fg, bg = colors.tab_inactive_bg },
	TabLineSel = { fg = colors.ui_fg, bg = colors.tab_active_bg, bold = true },
	TabLineFill = { bg = colors.status_bg },
	NvimTreeNormal = { fg = colors.ui_fg, bg = colors.sidebar_bg },
	NvimTreeWinSeparator = { fg = colors.sidebar_border, bg = colors.sidebar_border },
	Pmenu = { fg = colors.ui_fg, bg = colors.sidebar_bg },
	PmenuSel = { fg = colors.ui_fg, bg = colors.selection },
	Comment = { fg = colors.comment, italic = true },
	Constant = { fg = colors.builtin_const },
	String = { fg = colors.string },
	Character = { fg = colors.string },
	Number = { fg = colors.number },
	Boolean = { fg = colors.builtin_const },
	Float = { fg = colors.number },
	Identifier = { fg = colors.fg },
	Function = { fg = colors.library_func },
	Statement = { fg = colors.keyword },
	Conditional = { fg = colors.keyword },
	Repeat = { fg = colors.keyword },
	Label = { fg = colors.keyword },
	Operator = { fg = colors.fg },
	Keyword = { fg = colors.keyword },
	Exception = { fg = colors.keyword },
	PreProc = { fg = colors.preprocessor },
	Include = { fg = colors.preprocessor },
	Define = { fg = colors.preprocessor },
	Macro = { fg = colors.preprocessor },
	PreCondit = { fg = colors.preprocessor },
	Type = { fg = colors.class },
	StorageClass = { fg = colors.storage },
	Structure = { fg = colors.class },
	Typedef = { fg = colors.class },
	Special = { fg = colors.tag },
	Tag = { fg = colors.tag },
	Delimiter = { fg = colors.fg },
	SpecialComment = { fg = colors.comment, bold = true },
	Underlined = { underline = true },
	Bold = { bold = true },
	Italic = { italic = true },
	Error = { fg = "#ff0000", bg = "none", bold = true },
	Todo = { fg = colors.comment, bold = true },
	NormalFloat = { fg = colors.ui_fg, bg = colors.sidebar_bg },
	FloatBorder = { fg = colors.sidebar_border, bg = colors.sidebar_bg },
	FloatTitle = { fg = colors.keyword, bg = colors.sidebar_bg, bold = true },

	InputNormal = { fg = colors.ui_fg, bg = colors.bg },
	InputBorder = { fg = colors.sidebar_border },

	NeoTreeNormal = { fg = colors.ui_fg, bg = colors.sidebar_bg },
	NeoTreeNormalNC = { fg = colors.ui_fg, bg = colors.sidebar_bg },
	NeoTreeWinSeparator = { fg = colors.sidebar_border, bg = colors.sidebar_border },
	NeoTreeCursorLine = { bg = colors.line_hl },

	NeoTreeDirectoryName = { fg = colors.ui_fg },
	NeoTreeDirectoryIcon = { fg = colors.library_class },
	NeoTreeFileName = { fg = colors.fg },
	NeoTreeFileNameOpened = { fg = colors.ui_fg, bold = true },
	NeoTreeDimmed = { fg = colors.line_numbers_act },
	NeoTreeRootName = { fg = colors.keyword, bold = true },

	NeoTreeExpander = { fg = colors.line_numbers_act },
	NeoTreeIndentMarker = { fg = colors.sidebar_border },
	NeoTreeSymbolicLinkTarget = { fg = colors.tag, italic = true },

	NeoTreeGitModified = { fg = "#2f81a7" },
	NeoTreeGitConflict = { fg = colors.preprocessor },
	NeoTreeGitAdded = { fg = colors.comment },
	NeoTreeGitDeleted = { fg = colors.preprocessor },
	NeoTreeGitIgnored = { fg = colors.line_numbers },
	NeoTreeGitUntracked = { fg = colors.comment, italic = true },
	NeoTreeGitStaged = { fg = colors.comment },

	NeoTreeTabActive = { fg = colors.ui_fg, bg = colors.tab_active_bg, bold = true },
	NeoTreeTabInactive = { fg = colors.status_fg, bg = colors.tab_inactive_bg },
	NeoTreeTabSeparatorActive = { fg = colors.sidebar_border, bg = colors.tab_active_bg },
	NeoTreeTabSeparatorInactive = { fg = colors.sidebar_border, bg = colors.tab_inactive_bg },

	GitSignsAdd = { fg = colors.comment },
	GitSignsChange = { fg = colors.number },
	GitSignsDelete = { fg = colors.preprocessor },

	GitSignsAddLn = { bg = "#e8f4f1" },
	GitSignsChangeLn = { bg = "#eef9fe" },
	GitSignsDeleteLn = { bg = "#fdeeed" },

	GitSignsAddPreview = { fg = colors.comment, bg = "#e8f4f1" },
	GitSignsDeletePreview = { fg = colors.preprocessor, bg = "#fdeeed" },

	DiffAdd = { fg = "none", bg = "#e8f4f1" },
	DiffDelete = { fg = colors.line_numbers, bg = "#fdeeed" },
	DiffChange = { fg = "none", bg = "#eef9fe" },
	DiffText = { fg = "none", bg = "#d7f0fc", bold = true },

	diffAdded = { fg = colors.comment },
	diffRemoved = { fg = colors.preprocessor },
	diffLine = { fg = colors.tag },
	diffFile = { fg = colors.fg, bold = true },
	diffNewFile = { fg = colors.comment, bold = true },
	diffIndexLine = { fg = colors.line_numbers_act },

	StatusLineModeNormal = { fg = colors.ui_fg, bg = colors.tab_active_bg, bold = true },
	StatusLineModeInsert = { fg = "#ffffff", bg = colors.string, bold = true },
	StatusLineModeVisual = { fg = colors.ui_fg, bg = colors.selection, bold = true },
	StatusLineModeReplace = { fg = "#ffffff", bg = colors.preprocessor, bold = true },
	StatusLineModeCommand = { fg = "#ffffff", bg = colors.tag, bold = true },

	LuaLineDiffAdd = { fg = "#008E00", bg = "#fafafa" },
	LuaLineDiffChange = { fg = "#2f81a7", bg = "#fafafa", bold = true },
	LuaLineDiffDelete = { fg = colors.preprocessor, bg = "#fafafa" },

	lualine_c_diff_added_normal = { fg = "#008E00", bg = "#fafafa" },
	lualine_c_diff_changed_normal = { fg = "#2f81a7", bg = "#fafafa", bold = true },
	lualine_c_diff_removed_normal = { fg = colors.preprocessor, bg = "#fafafa" },

	DiagnosticError = { fg = "#d15b6d" },
	DiagnosticWarn = { fg = "#df9e5d" },
	DiagnosticInfo = { fg = "#2f81a7" },
	DiagnosticHint = { fg = colors.comment },

	DiagnosticVirtualTextError = { fg = "#d15b6d", bg = "#fdeeed", italic = true },
	DiagnosticVirtualTextWarn = { fg = "#df9e5d", bg = "#fef6ed", italic = true },
	DiagnosticVirtualTextInfo = { fg = "#2f81a7", bg = "#eef9fe", italic = true },
	DiagnosticVirtualTextHint = { fg = colors.comment, bg = "#e8f4f1", italic = true },

	DiagnosticUnderlineError = { undercurl = true, sp = "#d15b6d" },
	DiagnosticUnderlineWarn = { undercurl = true, sp = "#df9e5d" },
	DiagnosticUnderlineInfo = { underline = true, sp = "#2f81a7" },
	DiagnosticUnderlineHint = { underline = true, sp = colors.comment },

	LualineDiagnosticError = { fg = "#d15b6d", bg = "#fafafa" },
	LualineDiagnosticWarn = { fg = "#df9e5d", bg = "#fafafa" },
	LualineDiagnosticInfo = { fg = "#2f81a7", bg = "#fafafa" },
	LualineDiagnosticHint = { fg = colors.comment, bg = "#fafafa" },

	["@comment"] = { link = "Comment" },
	["@string"] = { link = "String" },
	["@number"] = { link = "Number" },
	["@keyword"] = { link = "Keyword" },
	["@storageclass"] = { link = "StorageClass" },
	["@type"] = { link = "Type" },
	["@type.builtin"] = { fg = colors.library_class },
	["@function"] = { link = "Function" },
	["@function.builtin"] = { fg = colors.library_func },
	["@variable"] = { fg = colors.fg },
	["@variable.builtin"] = { fg = colors.builtin_const },
	["@constant"] = { link = "Constant" },
	["@constant.builtin"] = { fg = colors.builtin_const },
	["@tag"] = { link = "Tag" },
	["@tag.attribute"] = { fg = colors.library_func },
}

for group, hl in pairs(highlights) do
	vim.api.nvim_set_hl(0, group, hl)

	package.loaded["lualine.themes.xcode-pastel"] = {
		normal = {
			a = { fg = colors.ui_fg, bg = colors.tab_active_bg, bold = true },
			b = { fg = colors.status_fg, bg = colors.status_bg },
			c = { fg = colors.status_fg, bg = colors.status_bg },
		},
		insert = {
			a = { fg = "#ffffff", bg = colors.string, bold = true },
			b = { fg = colors.status_fg, bg = colors.status_bg },
		},
		visual = {
			a = { fg = colors.ui_fg, bg = colors.selection, bold = true },
			b = { fg = colors.status_fg, bg = colors.status_bg },
		},
		replace = {
			a = { fg = "#ffffff", bg = colors.preprocessor, bold = true },
			b = { fg = colors.status_fg, bg = colors.status_bg },
		},
		command = {
			a = { fg = "#ffffff", bg = colors.tag, bold = true },
			b = { fg = colors.status_fg, bg = colors.status_bg },
		},
		inactive = {
			a = { fg = colors.line_numbers_act, bg = colors.status_bg },
			b = { fg = colors.line_numbers_act, bg = colors.status_bg },
			c = { fg = colors.line_numbers_act, bg = colors.status_bg },
		},
	}
end
