vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end

vim.o.background = "light"
vim.g.colors_name = "xcode-pastel"

local colors = {
	bg = "#ffffff",
	fg = "#656f81",
	ui_fg = "#434343",
	line_numbers = "#d4d4d4",
	line_numbers_act = "#818c96",
	line_hl = "#eeeeee",
	selection = "#b5d5ff",
	comment = "#89c0b4",
	preprocessor = "#ef8776",
	string = "#ee81b0",
	number = "#8adcfb",
	keyword = "#ee81b0",
	storage = "#ee81b0",
	builtin_const = "#ee81b0",
	class = "#89c0b4",
	tag = "#aa83e4",
	library_func = "#aa83e4",
	library_class = "#aa83e4",
	sidebar_bg = "#f8f8f7",
	sidebar_border = "#e5e5e5",
	status_bg = "#f6f6f5",
	status_fg = "#666666",
	tab_active_bg = "#f7f7f6",
	tab_inactive_bg = "#e9e9e8",
	search_match = "#a8ac94",
}

local highlights = {
	Normal = { fg = colors.fg, bg = colors.bg },
	NormalNC = { fg = colors.fg, bg = colors.bg },
	Cursor = { fg = colors.bg, bg = "#000000" },
	CursorLine = { bg = colors.line_hl },
	CursorColumn = { bg = colors.line_hl },
	ColorColumn = { bg = colors.line_hl },
	LineNr = { fg = colors.line_numbers, bg = colors.bg },
	CursorLineNr = { fg = colors.line_numbers_act, bg = colors.line_hl, bold = true },
	Visual = { bg = colors.selection },
	Search = { bg = colors.search_match, fg = "#000000" },
	IncSearch = { bg = colors.selection, fg = "#000000" },
	SignColumn = { bg = colors.bg },
	FoldColumn = { fg = colors.line_numbers, bg = colors.bg },
	Folded = { fg = colors.status_fg, bg = colors.sidebar_bg },
	VertSplit = { fg = colors.sidebar_border, bg = colors.bg },
	WinSeparator = { fg = colors.sidebar_border, bg = colors.bg },
	StatusLine = { fg = colors.status_fg, bg = colors.status_bg },
	StatusLineNC = { fg = colors.line_numbers, bg = colors.status_bg },
	TabLine = { fg = colors.status_fg, bg = colors.tab_inactive_bg },
	TabLineSel = { fg = colors.ui_fg, bg = colors.tab_active_bg, bold = true },
	TabLineFill = { bg = colors.status_bg },
	NvimTreeNormal = { fg = colors.ui_fg, bg = colors.sidebar_bg },
	NvimTreeWinSeparator = { fg = colors.sidebar_border, bg = colors.sidebar_border },
	NeoTreeNormal = { fg = colors.ui_fg, bg = colors.sidebar_bg },
	Pmenu = { fg = colors.ui_fg, bg = colors.sidebar_bg },
	PmenuSel = { fg = colors.ui_fg, bg = colors.selection },
	Comment = { fg = colors.comment, italic = true },
	Constant = { fg = colors.builtin_const },
	String = { fg = colors.string },
	Character = { fg = colors.string },
	Number = { fg = colors.number },
	Boolean = { fg = colors.builtin_const },
	Float = { fg = colors.number },
	Identifier = { fg = colors.fg },
	Function = { fg = colors.library_func },
	Statement = { fg = colors.keyword },
	Conditional = { fg = colors.keyword },
	Repeat = { fg = colors.keyword },
	Label = { fg = colors.keyword },
	Operator = { fg = colors.fg },
	Keyword = { fg = colors.keyword },
	Exception = { fg = colors.keyword },
	PreProc = { fg = colors.preprocessor },
	Include = { fg = colors.preprocessor },
	Define = { fg = colors.preprocessor },
	Macro = { fg = colors.preprocessor },
	PreCondit = { fg = colors.preprocessor },
	Type = { fg = colors.class },
	StorageClass = { fg = colors.storage },
	Structure = { fg = colors.class },
	Typedef = { fg = colors.class },
	Special = { fg = colors.tag },
	Tag = { fg = colors.tag },
	Delimiter = { fg = colors.fg },
	SpecialComment = { fg = colors.comment, bold = true },
	Underlined = { underline = true },
	Bold = { bold = true },
	Italic = { italic = true },
	Error = { fg = "#ff0000", bg = "none", bold = true },
	Todo = { fg = colors.comment, bold = true },

	["@comment"] = { link = "Comment" },
	["@string"] = { link = "String" },
	["@number"] = { link = "Number" },
	["@keyword"] = { link = "Keyword" },
	["@storageclass"] = { link = "StorageClass" },
	["@type"] = { link = "Type" },
	["@type.builtin"] = { fg = colors.library_class },
	["@function"] = { link = "Function" },
	["@function.builtin"] = { fg = colors.library_func },
	["@variable"] = { fg = colors.fg },
	["@variable.builtin"] = { fg = colors.builtin_const },
	["@constant"] = { link = "Constant" },
	["@constant.builtin"] = { fg = colors.builtin_const },
	["@tag"] = { link = "Tag" },
	["@tag.attribute"] = { fg = colors.library_func },
}

for group, hl in pairs(highlights) do
	vim.api.nvim_set_hl(0, group, hl)
end
